/**
 * Master Registry for CRFFL Weekly Contests & League Prize Payout Schedule
 */

export const LEAGUE_PAYOUTS = [
  {
    place: '1st Place (Champion)',
    amount: 180,
    label: '$180',
    tag: 'League Champion',
    description: 'CRFFL Championship Trophy, ring honors, and apex cash payout.',
    badgeColor: 'border-[#d4af37] text-[#d4af37] bg-[#d4af37]/10',
  },
  {
    place: '2nd Place (Runner-Up)',
    amount: 100,
    label: '$100',
    tag: 'Championship Game',
    description: 'Championship Match runner-up cash prize.',
    badgeColor: 'border-gray-400 text-gray-200 bg-gray-800/40',
  },
  {
    place: '3rd Place',
    amount: 50,
    label: '$50',
    tag: 'Bronze Match Winner',
    description: 'Third-place consolation final winner.',
    badgeColor: 'border-amber-700 text-amber-400 bg-amber-950/40',
  },
  {
    place: '4th Place',
    amount: 25,
    label: '$25',
    tag: 'Semifinalist',
    description: 'Fourth-place championship playoff finisher.',
    badgeColor: 'border-blue-700 text-blue-300 bg-blue-950/40',
  },
  {
    place: 'Toilet Bowl Winner',
    amount: 10,
    label: '$10',
    tag: 'Consolation Champ',
    description: 'Consolation bracket redemption champion.',
    badgeColor: 'border-emerald-700 text-emerald-300 bg-emerald-950/40',
  },
  {
    place: '14 Weekly Contests',
    amount: 140,
    label: '$140',
    subLabel: '($10 × 14)',
    tag: 'Regular Season Bounties',
    description: 'Weekly $10 bounty purse awarded across Weeks 1 through 14.',
    badgeColor: 'border-purple-700 text-purple-300 bg-purple-950/40',
  },
];

export const TOTAL_PRIZE_PURSE = 505;

export const WEEKLY_CONTESTS_MASTER = [
  {
    week_number: 1,
    contest_name: 'Breakout',
    description: 'The Starter who exceeds their projected points by the largest margin.',
    adjudication_date: '9/15/2026',
    prize: '$10',
    status: 'active',
    is_player_contest: true,
  },
  {
    week_number: 2,
    contest_name: 'Cold Shower',
    description: 'Highest scoring bench player.',
    adjudication_date: '9/22/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: true,
  },
  {
    week_number: 3,
    contest_name: 'Flexual Healing',
    description: 'Highest scoring player in a WR/RB/TE flex spot.',
    adjudication_date: '9/29/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: true,
  },
  {
    week_number: 4,
    contest_name: 'The Anchor',
    description: 'Lowest scoring player on a WINNING team (must be an uninjured starter, and not on a bye).',
    adjudication_date: '10/6/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: true,
  },
  {
    week_number: 5,
    contest_name: 'Air Raid',
    description: 'Highest combined score from your WR1 & WR2 spots.',
    adjudication_date: '10/13/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: true,
  },
  {
    week_number: 6,
    contest_name: 'Bad Beat',
    description: 'Highest scoring team that still loses.',
    adjudication_date: '10/20/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: false,
  },
  {
    week_number: 7,
    contest_name: 'Running Wild',
    description: 'Highest combined score from your RB1 & RB2 spots.',
    adjudication_date: '10/27/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: true,
  },
  {
    week_number: 8,
    contest_name: 'Ghost Town',
    description: 'Team with the most starters scoring in single digits (calculated before the decimal).',
    adjudication_date: '11/3/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: false,
  },
  {
    week_number: 9,
    contest_name: 'Highlight Reel',
    description: 'Starter with the longest run or reception from scrimmage (QB passing yards do not count, QB runs do count. Kickers/Punters do not count).',
    adjudication_date: '11/10/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: true,
  },
  {
    week_number: 10,
    contest_name: 'Managerial Malpractice',
    description: 'Team with the largest gap between their optimal score (The highest score they could have received) and their actual score.',
    adjudication_date: '11/17/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: false,
  },
  {
    week_number: 11,
    contest_name: 'Special Forces',
    description: 'Team with the highest combined Kicker and Defense score.',
    adjudication_date: '11/24/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: true,
  },
  {
    week_number: 12,
    contest_name: 'The Turkey',
    description: 'Lowest Team Score (Must field a complete Roster).',
    adjudication_date: '12/1/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: false,
  },
  {
    week_number: 13,
    contest_name: 'Nail Biter',
    description: 'Team with the smallest margin of victory.',
    adjudication_date: '12/8/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: false,
  },
  {
    week_number: 14,
    contest_name: 'The Hoarder',
    description: 'Team with the highest combined bench score.',
    adjudication_date: '12/15/2026',
    prize: '$10',
    status: 'upcoming',
    is_player_contest: false,
  },
];

