export const MASTHEAD_SAYINGS = [
  "Certified Loony Bin Resident",
  "Pop-Up Blockers Cannot Stop the Inevitable Loss",
  "The Only Newspaper That Smells Like Wet Pine and Regret",
  "Challenging the Ruling on the Field and Losing",
  "Server Status: Running on Pure Spite and Coffee",
  "The Official Paper of Record for Questionable Trade Vetoes",
  "Bringing You the News Before Your Trades Get Vetoed",
  "Wasting Office Hours Since Kickoff",
  "The Definitive Voice of Columbia River Fantasy Football",
  "Database Error: Too Many Excuses Detected",
  "Professional Lineup Bunglers",
  "Why Your Flex Play Is Actually a Curse",
  "Unbiased Reporting, Biased Waiver Claims",
  "Investigative Journalism Into Why Your First Round Pick Sucks",
  "Captivated in 4K High-Definition Misery (Note: Sourced from Whispers in the Wind...)",
  "The Tribunal Will Now Hear Your Excuses",
  "Bringing Meaning to Completely Meaningless Hobbies",
  "The Auto-Draft Defense Force",
  "Due Process? In This Economy?",
  "Professional Point Chasers",
  "Breaking News: The Commissioner Still Hasn’t Settled the Payouts",
  "The Daily Chronicle of Your Bad Decisions",
  "The Only Webpage Worth Staring At While You Should Be Working",
  "Capturing Every Single Drop of Regional Regret",
  "Direct Feed From the Underworld’s Waiver Wire",
  "Screaming at a Television Screen Doesn't Help, But We Do It Anyway",
  "Responsive Design for Unresponsive Managers",
  "Unlicensed Emotional Terrorism",
  "Official Notice: Stop Texting the Commissioner at 3 AM",
  "Pre-Season Optimism Crushed Week 1",
  "The Only Newspaper Printed Entirely in Salt",
  "Your Star Player Decided to Take a Personal Day",
  "State-Mandated Roster Abuse",
  "The Website Looks Great, Too Bad Your Team Doesn't",
  "Mock Drafts: Because Reality Hurts Too Much",
  "Local League Thrives on Pure Petty Drama",
  "Bureau of Broken Dreams",
  "Reaching for Defense in Round 8: A Memoir",
  "Up by 40 Points Going Into Monday Night and Still Losing",
  "Tracking Cookies Can't Handle This Much Salt",
  "Best Viewed With Tears in Your Eyes",
  "Columbia River’s Premier Source for Unsolicited Advice",
  "Columbia River Strong, Fantasy Weak",
  "The End of Civilization As We Draft It",
  "Weather Forecast: 100% Chance of Total Blowout",
  "Ministry of Silly Lineups",
  "Reliable News You Can Ignore Until Monday Morning",
  "Scoring the Second-Most Points Every Week Against the Guy Who Scores the Most",
  "Drafting with Your Heart and Regretting It by Quarter Two",
  "Pulitzer Prize Contender in Emotional Damage",
  "Local Man Ruins Fantasy Season Over a Chicken Sandwich",
  "The Voice of Reason You Will Completely Ignore",
  "Department of Bad Trades",
  "The Annual Rebuild Starts Immediately After the Draft",
  "If It Happened in the League, We’re Mocking It Here",
  "Protected Free Press and Incompetent Managers",
  "Fact-Checked by Nobody, Ever",
  "Chronic Overthinkers Anonymous",
  "Drafting Kickers in the 4th Round Since Forever",
  "Secured 256-Bit Encryption for Your Worthless Opinions",
  "Reporting From the Great Pacific Northwest Wasteland of Tight Ends",
  "Approved by 9/10 Raccoons",
  "Expert Analysis on Why Your Keeper Sucks",
  "Expertly Misinterpreting Training Camp Buzz",
  "Chronicling the Downfall of Your Season",
  "Your Grievance Has Been Filed in the Circular Cabinet",
  "Crossing the Bridge Into Roster Ruin",
  "Industrial Grade Copium",
  "Leading for 58 Minutes Just to Lose on a Garbage-Time Touchdown",
  "Snatching Victory From Nobody Because You Got Crushed",
  "Paper Thin, Just Like Your Championship Hopes",
  "All the News That’s Fit to Blame on the Kicker",
  "Because \"I Told You So\" Needs a Print Edition",
  "All the Stats Fit to Twist",
  "The Newspaper That Fits Comfortably Inside a Trash Can",
  "Championship Ring Chasing From the Comfort of Your Couch",
  "Sleeping on Sleepers That Stay Asleep All Season",
  "Safeguarding the Free Press and the Incompetent Manager",
  "Unverified Claims and Loud Noises!",
  "Your 12th Round Pick Is a Waste of Carbon",
  "Because Alcohol Alone Can't Fix a Four-Game Losing Streak",
  "Total Confidence in Players Who Will Score 1.2 Points",
  "Serving the Greater Columbia River Basin Since Last Tuesday",
  "League Integrity: We Think We Have Some Around Here Somewhere",
  "Snatching Defeat From the Jaws of Victory",
  "Powered Entirely by Caffeine and Bad Vibes",
  "Defensive Touchdowns Given Up Entirely to Spite You",
  "Backed by Science, Driven by Pure Spite",
  "Accountability Free Since Day One",
  "Delivering Carrier Pigeons With Concussions",
  "Extra, Extra! You Lost by 0.4 Points!",
  "Drafting a Backup Quarterback in Round 5 Like a Genius",
  "Sunday Night Heartbreak, Delivered Promptly",
  "Telepathically Linked to Your Benched Star Player",
  "Absolute Clown Show Production",
  "Bribing the Commissioner Since 202X",
  "Arthurian Legends and Other Terrible Draft Strategies",
  "Certified Loser Energy",
  "Zero Running Back Strategy: Zero Wins Resulted",
  "Managing the Columbia River Kangaroo Court",
  "Matchup Meltdowns & Monday Morning Madness",
  "Decoded From Ancient Tablets Found Near the Columbia River",
  "Institutional Grade Nonsense",
  "Turning Simple Game Scores Into Existential Crises",
  "Your Opponent Is Laughing at You Right Now",
  "Where Fact Meets Total Speculation",
  "Read All About Your Historic Collapse",
  "Winning the Consolation Bracket Is My Roman Empire",
  "Predicting the Future Poorly Since Kickoff",
  "Powered by HTML, CSS, and Broken Hopes",
  "Arthurian Legends, Sports Media Style",
  "Stat Corrections: The Gift That Ruins Your Week",
  "Investigating Collusion Since the Draft Went Sideways",
  "Capital Letters Make It True!",
  "Strategic Blunders Documented Daily",
  "Blowout City Population: You",
  "Scoring 180 Points When It Doesn't Matter, 65 When It Does",
  "Hard-Hitting Journalism and Soft-Hitting Lineups",
  "Dedicated to the Pursuit of Trash Talk",
  "Monday Morning Quarterbacks With Zero Eligibility",
  "Blowing a 99% Win Probability Like a Pro",
  "The Evergreen State’s Least Accurate Power Rankings",
  "Panic Buy Season Is Always Open",
  "Breathing That Crisp Washington Air While Losing by 50",
  "The Weekly Chronicle of Unfortunate Injuries",
  "Streaming Defense and Regretting Life Choices",
  "Proudly Promoting Impulsive Roster Moves",
  "Documenting Your Slow Descent Into Madness",
  "Proving Beyond a Doubt That the Draft Order Was Rigged",
  "The Curse of the Projected Winner",
  "Streaming Incompetence Live to the World",
  "Please Disable Your Adblocker, We Need the Ego Boost",
  "Sourced From Whispers in the Wind and Salty Tears",
  "Absolute Cinematic Trash",
  "Surviving the Gray Winters Through Fantasy Football Coping Mechanisms",
  "Refreshing This Page Won't Make Your Players Score More Points",
  "Arbitrary Rulings Made Fresh Daily",
  "Sunset Boulevard of Broken Roster Dreams",
  "Down by the River, Bleeding Fantasy Points",
  "Surviving on Pure Delusion and Cold Pizza",
  "The League Office Denies All Allegations of Bias",
  "Monumental Triviality at Its Finest",
  "Drop the Kicker, Hire a Therapist!",
  "Yelling at Spreadsheets Until They Make Sense!",
  "Certified Organic, Free-Range Panic",
  "Columbia River’s Least Accredited News Outlet",
  "Your Team Is a Tragic Comedy in Three Acts",
  "The Annual Tradition of Ruining Your Sunday Afternoon in August",
  "Professional Opinions on Amateur Mistakes",
  "Transmitted Directly Into Your Sleep Deprivation",
  "Kangaroo Court Is Now in Session",
  "Brought to You by a Script That Is Probably About to Crash",
  "Click Here to Validate Your Poor Life Choices",
  "Because Screaming Into a Pillow Wasn’t Public Enough",
  "Refreshing Constantly Waiting for a Trade That Will Never Come",
  "The Only Newspaper That Blames Everyone But You",
  "Trusting the Projection That Lied to You Last Year",
  "Disputed Scoring Changes: Our Specialty",
  "CSS Styling Can’t Fix Your Record",
  "Optimizing Despair Since Week 1",
  "Error 404: Championship Team Not Found",
  "Your Wife Thinks This Is Silly, and She’s Right",
  "Etched Into Stone Tablets That No One Reads",
  "Maximum Overdrive Apathy!",
  "Loading Next Disappointment… Please Wait",
  "Clearing Your Cache Won't Clear Your Conscience",
  "From the Gorge to the Gridiron: Total Chaos",
  "Powered by Hamsters Running on Broken Dreams",
  "Suboptimal Performance Art",
  "Chaos Coordinator Weekly",
  "Mastermasterpiece of Mediocrity",
  "Generated by an AI That Just Wants a Nap",
  "At Least Your Actual Life Is Going Great",
  "100% Certified Grade-A Nonsense",
  "Navigating the Cascades of Poor Lineup Choices",
  "Caught in the I-5 Traffic Jam of Despair",
  "Broadcast Live From Inside a Cardboard Box",
  "Written by Monkeys With Typewriters and Zero Football IQ",
  "Broadcast From a Secret Bunker Beneath the Stadium",
  "Mathematical Improbability of Improvement",
  "Fighting the Pacific Northwest Rain With Pure Salt",
  "Mathematically Unlikely to Ever Improve",
  "Reporting Live From the Banks of the Mighty Columbia",
  "Keeping Portland-Adjacent Weirdness Alive in Fantasy",
  "The Most Trusted News Source Between Vancouver and Nowhere",
  "Cloudy With a Chance of Complete Roster Collapse",
  "Believing in Your Late-Round Sleepers So You Don’t Have to Cry",
  "Bench Points: Where Your True Genius Lies",
  "The Art of Starting the Wrong Guy Every Single Time",
  "Losing to the Inactive Team Because of Course You Did",
  "WHY DID YOU BENCH HIM?!",
  "It Was a Catch, You Cowards!",
  "HE WAS QUESTIONABLE FOR A REASON!",
  "STOP PLAYING INJURED PLAYERS YOU IDIOT!",
  "THE NUMBERS DON'T LIE, BUT YOUR WIFE DOES",
  "FIRE EVERYONE ON YOUR ROSTER INTO THE SUN",
  "WHY IS HE GETTING CARRIES IN THE FOURTH QUARTER?!",
  "THAT WAS CLEARLY A LATERAL!",
  "RAGE DROP YOUR ENTIRE TEAM, SEE IF WE CARE",
  "WHO WROTE THIS TRASH? WE DON'T KNOW EITHER!",
  "We Survived the Bye Week Apocalypse!"
];

